services:
  kc:
    image: quay.io/keycloak/keycloak:23.0.6
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_DATABASE: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 'Start123!'
    command: ["start-dev"]
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 127.0.0.1:8080:8080/tcp
    volumes:
      - ./script:/opt/script

  postgres:
    image: docker.io/postgres:16
    environment:
      POSTGRES_PASSWORD: "whatever this doesn't even matter anyway as we're not using the superuser"
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=en --encoding=UTF8"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./pg-initdb.sql:/docker-entrypoint-initdb.d/00-pg-initdb.sql:ro
